title: Luyang'Log
name: "Luyang's Blog"
author: Luyang Zan
baseurl: "/zanluyang.github.io"
description: Document my learning notes.
profile_url: "http://zanluyang.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
